server:
  port: 8761
spring:
  application:
    name: iportman-eurekaserver
  config:
    import:
    - configserver:http://localhost:8889/
  cloud:
    config:
      username: Rocky
      password: Rocky
management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - refresh       
   