

server:
  port: 8889

spring:
  cloud:
    config:
      server:
        git:
          uri: http://192.168.99.202/rangaswamy/iportman-configserver.git
          username: Rangaswamy
          password: Rocky734@#?
          default-label: master
          refresh-rate: 120
  security:
    user:
      name: Rocky
      password: Rocky  
      roles:
      - admin    
          
          
# uri: https://username:patTocken@github.com/rangaswamy/iportman-configserver.git          