server:
  port: 8005
spring:
  application:
    name: generalcargo-config
  config:
    import:
    - configserver:http://localhost:8889
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
      
management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - refresh      
        
    
  
      